apiVersion: v1
kind: Secret
metadata: # kpt-merge: /${APP_NAME:=app}-defaultconfig
  name: ${APP_NAME:=app}-defaultconfig
  annotations:
    internal.kpt.dev/upstream-identifier: '|Secret|default|${APP_NAME:=app}-defaultconfig'
# TODO: specify the default configuration for your app
#stringData:
#  EXAMPLE_VAR: "value-a"
